version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      - PG_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gisdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: